### ISSUE TITLE
Hint color

### ISSUE THREAD

**Issue by mathieudebrito** [wrapp/floatlabelededittext#32]
Hi,
how can I change the hint color ?

BTW : Awesome lib :)

**Comment by santoshkumar1227** [comment]
how to change the FloatLabeledEditText hint color dynamically from activity/fragment?

`
down vote
favorite
My requirement is to change the FloatLabeledEditText hint color dynamically using JAVA code..

below is the XML code to generate FloatLabeledEditText with default color

```
    <com.wrapp.floatlabelededittext.FloatLabeledEditText
    android:id="@+id/float_email"
    android:layout_width="match_parent"
    android:layout_height="wrap_content"
    android:layout_marginTop="@dimen/_10dp"
    float:fletTextAppearance="@style/floatlabelededittext">

    <EditText
        android:id="@+id/et_email"
        style="@style/EditTextWithBlackMediumSizeWithoutLeftAndTopPadding10"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:background="@null"
        android:drawableEnd="@drawable/ic_email"
        android:hint="@string/email"
        android:inputType="textEmailAddress" />
</com.wrapp.floatlabelededittext.FloatLabeledEditText>`
```

I added color with style using tag float:fletTextAppearance="@style/floatlabelededittext". but not sure how to add this style dynamically using java code or atleast i need to change the text hint color
