### ISSUE TITLE
InflateException 

### ISSUE THREAD

**Issue by Odaym** [wrapp/floatlabelededittext#49]
I've been getting this exception with the new support library, using AS 3.0 and API 26, https://hastebin.com/utujofiyip.sql

it was working just fine before the update, any idea?

**Comment by heinrisch** [comment]
I would recommend switching over to the support design library for a better experience :)

https://stackoverflow.com/questions/26458436/android-edittext-view-floating-hint-in-material-design

**Comment by Odaym** [comment]
yea I think so too, hopeless to ask here honestly after this much time, eh, thanks again!
